# Generated by Django 5.1.7 on 2025-06-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundingProject', '0003_alter_category_options_alter_category_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='../Crowd_funding_reactUI/media/projects/'),
        ),
    ]
