# Generated by Django 5.1.7 on 2025-06-24 08:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundingProject', '0004_alter_projectimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='projects/'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('project', 'user')},
        ),
    ]
