# Generated by Django 5.2.1 on 2025-06-02 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custom_user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
