# Generated by Django 5.2.1 on 2025-06-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_alter_custom_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='first_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='last_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
