# Generated by Django 5.2.1 on 2025-06-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_alter_custom_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
