# Generated by Django 5.1.7 on 2025-06-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_alter_custom_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='token',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
