# Generated by Django 5.1.7 on 2025-06-24 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_custom_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='token_expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 25, 0, 8, 51, 88533, tzinfo=datetime.timezone.utc)),
        ),
    ]
