# Generated by Django 5.1.7 on 2025-06-24 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_custom_user_token_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='token_expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 25, 8, 3, 12, 243755, tzinfo=datetime.timezone.utc)),
        ),
    ]
